# Generated by Django 5.1.1 on 2024-09-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='machine',
            table='machine',
        ),
    ]
